package com.platform.jupiter.config;

import org.springframework.boot.context.properties.ConfigurationProperties;

@ConfigurationProperties(prefix = "app")
public record AppProperties(
        String namespace,
        String registry,
        String baseImage,
        String jupyterUrl,
        String frontendUrl,
        String apiUrl,
        String gatewayUrl,
        String launcherUrl,
        String adminerUrl,
        String artifactRegistryUrl,
        String artifactRegistryUsername,
        String artifactRegistryPassword,
        String kafkaUrl,
        String elkUrl,
        String pypiProxyUrl,
        String pypiProxyHost,
        String externalHost,
        String notebookUser,
        String mariadbUrl,
        String mariadbUsername,
        String mariadbPassword,
        String workspaceNode,
        String assistantDataRoot,
        String conversationRoot,
        String workspaceRoot,
        String snapshotRoot,
        String ragRoot,
        String ragSourceRoot,
        String qdrantUrl,
        String ragCollection,
        Integer ragEmbeddingDimensions,
        Boolean ragWeatherEnabled,
        String weatherApiBaseUrl,
        String weatherLocations,
        String kakaoRestApiKey,
        String codexApiBaseUrl,
        String codexModel,
        String codexCliPath,
        String codexCliBinDir,
        String geminiApiKey,
        String openAiApiKey,
        String openAiModel,
        String grokApiKey,
        Long pythonTimeoutSeconds,
        Boolean enableCodexCliMode,
        Boolean enableTravelPlanCodexCliMode,
        String geminiOauthClientId,
        String geminiOauthClientSecret,
        String geminiOauthRedirectUri) {
}
